---

# ------------------------------------------
# Database settings
# ------------------------------------------
postgresql_version: 15


miarec_db_name: "miarecdb"
miarec_db_user: "miarec"
miarec_db_password: "{{ secret_db_password | default('password') }}"
miarec_db_port: "{{ install_pgbouncer|default(False) | ternary(6432, 5432) }}"

# Define similar variables for MiaRecWeb role
miarecweb_db_name: "{{ miarec_db_name }}"
miarecweb_db_user: "{{ miarec_db_user }}"
miarecweb_db_password: "{{ miarec_db_password }}"
miarecweb_db_port: "{{ miarec_db_port }}"

# -------------------------------
# PGBouncer settings
# -------------------------------
install_pgbouncer: yes

# -------------------------------
# Redis settings
# -------------------------------
redis_port: 6379
redis_install_from_source: false

# -------------------------------
# Python settings
# -------------------------------
python_install_from_source: false

python_verify_gpg_signature: true

python_cleanup_downloads: true
python_force_install: false


# -------------------------------
# Sox settings
# -------------------------------
sox_install_from_source: false

# Download the required sox components from MiaRec web-site to avoid dependencies on sourceforge.net and other sites
sox_download_url: "https://miarec-download.s3.amazonaws.com/sox-{{ sox_version }}.tar.gz"
libmad_download_url: "https://miarec-download.s3.amazonaws.com/libmad-{{ libmad_version }}.tar.gz"
libogg_download_url: "https://miarec-download.s3.amazonaws.com/libogg-{{ libogg_version }}.tar.gz"
flac_download_url: "https://miarec-download.s3.amazonaws.com/flac-{{ flac_version }}.tar.xz"
lame_download_url: "https://miarec-download.s3.amazonaws.com/lame-{{ lame_version }}.tar.gz"


